import type { Exhibit } from "./types"

export const exhibits: readonly Exhibit[] = [
  {
    slug: "singapore-marina-bay",
    collectionNumber: "006",
    title: "滨海湾：与你看夜景",
    summary: "从滨海堤坝草坪望向金沙的 Q 版旅行纪念景观。",
    description: "前景是滨海堤坝的弧形屋顶草坪、步道栏杆与柱廊，两位 Q 版旅人停在其中；层叠绿地向远处延伸，金沙、CBD 与摩天轮共同构成天际线。模型依据旅行记忆压缩纵深与非重点地段，并非等比例地图复原。",
    tags: ["新加坡", "滨海湾", "夜景", "建筑微缩", "旅行纪念"],
    tools: ["Blender"],
    cover: "/covers/singapore-marina-bay.jpg",
    model: "/models/singapore-marina-bay.glb",
    featured: true,
    presentation: {
      layout: "center-stage",
      scene: "cold-chamber",
      palette: ["#101E28", "#52794D", "#EDC789"],
      lightingPresets: ["rim", "warm"],
    },
    animation: { mode: "static" },
    share: { image: "/share/singapore-marina-bay.png" },
  },
  {
    slug: "pochita",
    collectionNumber: "005",
    title: "波奇塔：链锯小恶魔",
    summary: "橙色小恶魔波奇塔以四足站姿抬起额前链锯。",
    description: "以原著和官方等身软胶手办比例为依据重新雕塑，保留连续橙色犬形身体、侧置大眼、额前链锯、顶部黑色把手、四只短腿与拉绳尾巴。",
    tags: ["波奇塔", "二次元手办", "链锯恶魔", "萌系"],
    tools: ["Blender"],
    cover: "/covers/pochita.jpg",
    model: "/models/pochita.glb",
    presentation: {
      layout: "center-stage",
      scene: "warm-cabinet",
      palette: ["#11151C", "#F04A20", "#AFC4D3"],
      lightingPresets: ["warm", "rim"],
    },
    animation: { mode: "static" },
    share: { image: "/share/pochita.png" },
  },
  {
    slug: "green-core",
    collectionNumber: "001",
    title: "翠核标本",
    summary: "一枚被当作未知生命核心保存的绿色标本。",
    description: "它没有角色履历，却像某种沉睡生命留下的核心。第一件馆藏用它验证材质、微小物体构图与暖色陈列。",
    tags: ["有机", "静态", "材质"],
    cover: "/covers/avocado.jpg",
    model: "/models/avocado.glb",
    presentation: {
      layout: "center-stage",
      scene: "warm-cabinet",
      palette: ["#263d1f", "#92b85c", "#b47b3e"],
      lightingPresets: ["warm", "rim"],
    },
    animation: { mode: "static" },
    share: { image: "/share/green-core.png" },
    attribution: { creator: "Microsoft", source: "Khronos glTF Sample Assets", license: "CC0-1.0" },
  },
  {
    slug: "silent-observer",
    collectionNumber: "002",
    title: "静默观测者",
    summary: "一台来自旧时代的观测装置，被重新安置在冷光舱室。",
    description: "机械结构与镜头形成类似角色面孔的轮廓，用于验证宽体模型、偏置叙事和冷色灯光。",
    tags: ["机械", "静态", "旧物"],
    cover: "/covers/antique-camera.jpg",
    model: "/models/antique-camera.glb",
    presentation: {
      layout: "story-offset",
      scene: "cold-chamber",
      palette: ["#1d2633", "#7890b5", "#c28b55"],
      lightingPresets: ["top", "scan"],
    },
    animation: { mode: "static" },
    share: { image: "/share/silent-observer.png" },
    attribution: { creator: "UX3D", source: "Khronos glTF Sample Assets", license: "CC0-1.0" },
  },
  {
    slug: "wilderness-messenger",
    collectionNumber: "003",
    title: "旷野信使",
    summary: "一只携带三段行动记忆、穿行于星雾之间的信使。",
    description: "横向体态与多段骨骼动画用于验证沉浸构图、动画选择和移动端镜头边界。",
    tags: ["生物", "动画", "信使"],
    cover: "/covers/fox.jpg",
    model: "/models/fox.glb",
    presentation: {
      layout: "immersive",
      scene: "star-mist",
      palette: ["#18293d", "#8ea9d8", "#d4a56a"],
      lightingPresets: ["moon", "starlight"],
    },
    animation: { mode: "manual", clip: "Survey" },
    audio: { ambientTrack: "/audio/fox-ambient.wav" },
    share: { image: "/share/wilderness-messenger.png" },
    attribution: { creator: "PixelMannen et al.", source: "Khronos glTF Sample Assets", license: "CC0-1.0 AND CC-BY-4.0" },
  },
]
